/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class dashboardMenu extends javax.swing.JFrame {

    /**
     * Creates new form dashboardMenu
     */
    
    String nama = login.getU_nama();
    String level = login.getU_level();

    public void hakAksesAdmin() {

    }

    public void hakAksesKaryawan() {
        btnDataAdmin.setEnabled(false);
    }

   
    public dashboardMenu() {
        initComponents();
        labelNama.setText("Semangat Pagi " + nama + " !");
        labelHakAkses.setText(" Posisi Anda : " + level);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnDataInvestor = new javax.swing.JButton();
        btnDataTransaksi = new javax.swing.JButton();
        btnDataAdmin = new javax.swing.JButton();
        btnDataKambing = new javax.swing.JButton();
        TambahDataKambing = new javax.swing.JButton();
        btnCetakDataTransaksi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelHakAkses = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Capra App");

        javax.swing.GroupLayout headerLogoLayout = new javax.swing.GroupLayout(headerLogo);
        headerLogo.setLayout(headerLogoLayout);
        headerLogoLayout.setHorizontalGroup(
            headerLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLogoLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel2)
                .addContainerGap(505, Short.MAX_VALUE))
        );
        headerLogoLayout.setVerticalGroup(
            headerLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(headerLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 80));

        btnDataInvestor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnDataInvestor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/data.png"))); // NOI18N
        btnDataInvestor.setText("Data Investor");
        btnDataInvestor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataInvestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataInvestorActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataInvestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 400, 60));

        btnDataTransaksi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnDataTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/newtransaksi.png"))); // NOI18N
        btnDataTransaksi.setText("Data Transaksi");
        btnDataTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 400, 60));

        btnDataAdmin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnDataAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/newuser.png"))); // NOI18N
        btnDataAdmin.setText("Data Admin");
        btnDataAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 400, 60));

        btnDataKambing.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnDataKambing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/folder.png"))); // NOI18N
        btnDataKambing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataKambing.setLabel("Data Kambing");
        btnDataKambing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataKambingActionPerformed(evt);
            }
        });
        jPanel1.add(btnDataKambing, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 400, 60));

        TambahDataKambing.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TambahDataKambing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/goat1.png"))); // NOI18N
        TambahDataKambing.setText("Tambah Data Kambing");
        TambahDataKambing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TambahDataKambing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahDataKambingActionPerformed(evt);
            }
        });
        jPanel1.add(TambahDataKambing, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 400, 60));

        btnCetakDataTransaksi.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnCetakDataTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/40printer.png"))); // NOI18N
        btnCetakDataTransaksi.setText("Cetak Data Transaksi");
        btnCetakDataTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetakDataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakDataTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetakDataTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 400, 60));

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 140, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 0)));

        labelNama.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 400, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 0)));

        labelHakAkses.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelHakAkses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHakAkses, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHakAkses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 400, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/bg_menu.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataInvestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataInvestorActionPerformed
        // TODO add your handling code here:
        data_investor dataInvestor = new data_investor(this, rootPaneCheckingEnabled);
        dataInvestor.setLocationRelativeTo(this);
        dataInvestor.setVisible(true);
    }//GEN-LAST:event_btnDataInvestorActionPerformed

    private void btnDataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataTransaksiActionPerformed
        // TODO add your handling code here:
        data_transaksi dataTransaksi = new data_transaksi(this, rootPaneCheckingEnabled);
        dataTransaksi.setLocationRelativeTo(this);
        dataTransaksi.setVisible(true);
    }//GEN-LAST:event_btnDataTransaksiActionPerformed

    private void btnDataKambingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataKambingActionPerformed
        // TODO add your handling code here:
        data_kambinglama dataTransaksi = new data_kambinglama(this, rootPaneCheckingEnabled);
        dataTransaksi.setLocationRelativeTo(this);
        dataTransaksi.setVisible(true);
    }//GEN-LAST:event_btnDataKambingActionPerformed

    private void btnDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataAdminActionPerformed
        // TODO add your handling code here:
        data_user dataUser = new data_user(this, rootPaneCheckingEnabled);
        dataUser.setLocationRelativeTo(this);
        dataUser.setVisible(true);
    }//GEN-LAST:event_btnDataAdminActionPerformed

    private void TambahDataKambingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahDataKambingActionPerformed
        // TODO add your handling code here:
        data_kambingbaru dataTransaksiBaru = new data_kambingbaru(this, rootPaneCheckingEnabled);
        dataTransaksiBaru.setLocationRelativeTo(this);
        dataTransaksiBaru.setVisible(true);
    }//GEN-LAST:event_TambahDataKambingActionPerformed

    private void btnCetakDataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakDataTransaksiActionPerformed
        // TODO add your handling code here:
         cetakDataTransaksi cetak = new cetakDataTransaksi(this, rootPaneCheckingEnabled);
        cetak.setLocationRelativeTo(this);
        cetak.setVisible(true);
    }//GEN-LAST:event_btnCetakDataTransaksiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        String objBtn[] = {"IYA","TIDAK"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah anda ingin keluar?","Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, objBtn, objBtn[1]);
        if(pilihan == 0){
            login lg = new login();
            lg.setLocationRelativeTo(null);
            lg.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TambahDataKambing;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCetakDataTransaksi;
    private javax.swing.JButton btnDataAdmin;
    private javax.swing.JButton btnDataInvestor;
    private javax.swing.JButton btnDataKambing;
    private javax.swing.JButton btnDataTransaksi;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JPanel headerLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelHakAkses;
    private javax.swing.JLabel labelNama;
    // End of variables declaration//GEN-END:variables
}
